### ISSUE TITLE
Set boot parameters for 5 iv

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-nagara/main#5]
Please set boot parameters in 

https://github.com/sailfishos-sony-nagara/droid-hal-img-boot-sony-nagara/blob/main/rpm/droid-hal-pdx224-img-boot.spec

See [corresponding section of HADK](https://github.com/sailfishos-sony-nagara/main/wiki/HADK-for-Sony-Nagara-devices#boot-images) for commands. Note that 1 iv boot commands have been partially merged with the ones used in Zambezi - let's use the same notation for the both devices and will fix those if needed together later

**Comment by b100dian** [comment]
```
$ ~/android$ system/tools/mkbootimg/unpack_bootimg.py --boot_img out/target/product/pdx224/boot.img --format=mkbootimg
--header_version 4 --os_version 14.0.0 --os_patch_level 2024-09 --kernel out/kernel --ramdisk out/ramdisk --cmdline ''

$ /android$ system/tools/mkbootimg/unpack_bootimg.py --boot_img out/target/product/pdx224/vendor_boot.img --format=mkbootimg
--header_version 4 --pagesize 0x00001000 --base 0x00000000 --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dtb_offset 0x0000000001f00000 --vendor_cmdline 'coherent_pool=8M printk.devkmsg=on androidboot.fstab_suffix=pdx224 bootconfig' --board '' --dtb out/dtb --vendor_bootconfig out/bootconfig --ramdisk_type 1 --ramdisk_name '' --vendor_ramdisk_fragment out/vendor_ramdisk00

```

It seems they are already correct from my undestanding. Not sure about the last token on the second line that mentions just ` --vendor_boot` but that's the same for pdx223

**Comment by rinigus** [comment]
I had the same ramdisk_fragmet and others. decided to take components from zambezi instead. At least the both devices are in sync and if it is buggy for one, it will be buggy for the other one as well. Closing here
